topics:
  - in-app-purchase 
  - flutter-in-app-purchase  
  - storekit-2
  - billing-client-8
  - payment

name: flutter_inapp_purchase_plus
description: In App Purchase plugin for flutter. This project has been forked by
  flutter_inapp_purchase and we are willing to share same experience with that on
  flutter_inapp_purchase.
version: 1.0.4
homepage: https://github.com/IMHitesh/flutter_inapp_purchase_plus/blob/main/pubspec.yaml
environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  meta: ^1.9.1
  platform: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  test: ^1.24.3

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.noble.flutterinapppurchaseplus
        pluginClass: FlutterInappPurchasePlugin
        mainClass: FlutterInappPurchasePlugin
      ios:
        pluginClass: FlutterInappPurchasePlugin